import { minerals, SHIP_VOLUMES } from "../../helpers/minerals";

const { veldsparFamily, scorditeFamily, omberFamily } = minerals;

export const mineralDefs = {
  [veldsparFamily.normal.veldspar.name]: {
    name: veldsparFamily.normal.veldspar.name,
    priceStep: 2,
    fromBuyPrice: 16,
    toBuyPrice: 40,
    rowValues: {
      rawminUnitVolume: 0.1,
      shipVolume: 46200,
      rawminQty: 0,
      rawminTotalCost: 0,
      cminUnitVolume: 0.15,
      cminVolume: 0,
      cminQty: 0,
      cminSellPrice: 2800,
      grosProfit: 0,
      brokerFee: 0,
      tax: 0,
      netProfit: 0,
      profit: 0,
      profitP: 0,
    },
  },
  [veldsparFamily.normal.denseVeldspar.name]: {
    name: veldsparFamily.normal.denseVeldspar.name,
    priceStep: 2,
    fromBuyPrice: 16,
    toBuyPrice: 45,
    rowValues: {
      rawminUnitVolume: 0.1,
      shipVolume: 46200,
      rawminQty: 0,
      rawminTotalCost: 0,
      cminUnitVolume: 0.15,
      cminVolume: 0,
      cminQty: 0,
      cminSellPrice: 3300,
      grosProfit: 0,
      brokerFee: 0,
      tax: 0,
      netProfit: 0,
      profit: 0,
      profitP: 0,
    },
  },
  [scorditeFamily.normal.scordite.name]: {
    name: scorditeFamily.normal.scordite.name,
    priceStep: 2,
    fromBuyPrice: 16,
    toBuyPrice: 50,
    rowValues: {
      rawminUnitVolume: 0.15,
      shipVolume: 46200,
      rawminQty: 0,
      rawminTotalCost: 0,
      cminUnitVolume: 0.19,
      cminVolume: 0,
      cminQty: 0,
      cminSellPrice: 4500,
      grosProfit: 0,
      brokerFee: 0,
      tax: 0,
      netProfit: 0,
      profit: 0,
      profitP: 0,
    },
  },
  [scorditeFamily.normal.condensedScordite.name]: {
    name: scorditeFamily.normal.condensedScordite.name,
    priceStep: 1,
    fromBuyPrice: 16,
    toBuyPrice: 55,
    rowValues: {
      rawminUnitVolume: 0.15,
      shipVolume: 46200,
      rawminQty: 0,
      rawminTotalCost: 0,
      cminUnitVolume: 0.19,
      cminVolume: 0,
      cminQty: 0,
      cminSellPrice: 4000,
      grosProfit: 0,
      brokerFee: 0,
      tax: 0,
      netProfit: 0,
      profit: 0,
      profitP: 0,
    },
  },
  //   [AZURE_PLAGIOCLASE]: {
  //     name: AZURE_PLAGIOCLASE,
  //     priceStep: 1,
  //     fromBuyPrice: 10,
  //     toBuyPrice: 60,
  //     rowValues: {
  //       rawminUnitVolume: 0.35,
  //       shipVolume: 46200,
  //       rawminQty: 0,
  //       rawminTotalCost: 0,
  //       cminUnitVolume: 0.15,
  //       cminVolume: 0,
  //       cminQty: 0,
  //       cminSellPrice: 8200,
  //       grosProfit: 0,
  //       brokerFee: 0,
  //       tax: 0,
  //       netProfit: 0,
  //       profit: 0,
  //       profitP: 0,
  //     },
  //   },
  [omberFamily.normal.goldenOmber.name]: {
    name: omberFamily.normal.goldenOmber.name,
    priceStep: omberFamily.normal.goldenOmber.priceStep,
    fromBuyPrice: omberFamily.normal.goldenOmber.fromBuyPrice,
    toBuyPrice: omberFamily.normal.goldenOmber.toBuyPrice,
    rowValues: {
      rawminUnitVolume: omberFamily.normal.goldenOmber.volume,
      shipVolume: SHIP_VOLUMES.MIASMOS,
      rawminQty: 0,
      rawminTotalCost: 0,
      cminUnitVolume: omberFamily.compresssed.goldenOmber.volume,
      cminVolume: 0,
      cminQty: 0,
      cminSellPrice: omberFamily.compresssed.goldenOmber.cminSellPrice,
      grosProfit: 0,
      brokerFee: 0,
      tax: 0,
      netProfit: 0,
      profit: 0,
      profitP: 0,
    },
  },
  //   [FIERY_KERNITE]: {
  //     name: FIERY_KERNITE,
  //     priceStep: 5,
  //     fromBuyPrice: 100,
  //     toBuyPrice: 200,
  //     rowValues: {
  //       rawminUnitVolume: 1.2,
  //       shipVolume: 46200,
  //       rawminQty: 0,
  //       rawminTotalCost: 0,
  //       cminUnitVolume: 0.19,
  //       cminVolume: 0,
  //       cminQty: 0,
  //       cminSellPrice: 24000,
  //       grosProfit: 0,
  //       brokerFee: 0,
  //       tax: 0,
  //       netProfit: 0,
  //       profit: 0,
  //       profitP: 0,
  //     },
  //   },
  // [MERCOXIT]: {
  //   name: MERCOXIT,
  //   priceStep: 3000,
  //   fromBuyPrice: 50000,
  //   toBuyPrice: 100000,
  //   rowValues: {
  //     rawminUnitVolume: 40,
  //     shipVolume: 46200,
  //     rawminQty: 0,
  //     rawminTotalCost: 0,
  //     cminUnitVolume: 0.1,
  //     cminVolume: 0,
  //     cminQty: 0,
  //     cminSellPrice: 40000000,
  //     grosProfit: 0,
  //     brokerFee: 0,
  //     tax: 0,
  //     netProfit: 0,
  //     profit: 0,
  //     profitP: 0,
  //   },
  // },
  //   [PRISTINE_JASPET]: {
  //     name: PRISTINE_JASPET,
  //     priceStep: 15,
  //     fromBuyPrice: 200,
  //     toBuyPrice: 500,
  //     rowValues: {
  //       rawminUnitVolume: 1.2,
  //       shipVolume: 46200,
  //       rawminQty: 0,
  //       rawminTotalCost: 0,
  //       cminUnitVolume: 0.15,
  //       cminVolume: 0,
  //       cminQty: 0,
  //       cminSellPrice: 50000,
  //       grosProfit: 0,
  //       brokerFee: 0,
  //       tax: 0,
  //       netProfit: 0,
  //       profit: 0,
  //       profitP: 0,
  //     },
  //   },
  //   [SPODUMAIN]: {
  //     name: SPODUMAIN,
  //     priceStep: 200,
  //     fromBuyPrice: 4000,
  //     toBuyPrice: 15000,
  //     rowValues: {
  //       rawminUnitVolume: 16,
  //       shipVolume: 46200,
  //       rawminQty: 0,
  //       rawminTotalCost: 0,
  //       cminUnitVolume: 28,
  //       cminVolume: 0,
  //       cminQty: 0,
  //       cminSellPrice: 720000,
  //       grosProfit: 0,
  //       brokerFee: 0,
  //       tax: 0,
  //       netProfit: 0,
  //       profit: 0,
  //       profitP: 0,
  //     },
  //   },
};
